CREATE TYPE status_pedido_enum AS ENUM(
    'CRIADO',
    'CONFIRMADO',
    'ENTREGUE',
    'CANCELADO'
);

CREATE TABLE IF NOT EXISTS pedidos(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subtotal DECIMAL(10.2) NOT NULL,
    taxa_frete DECIMAL(10.2) DEFAULT 0.00,
    valor_total DECIMAL(10.2) NOT NULL,
    data_hora_criacao,
    data_confirmacao,
    data_cancelamento,
    data_entrega,
    status_pedido status_pedido_enum NOT NULL

    CONSTRAINT
);


