CREATE TABLE IF NOT EXISTS itens_pedido(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(10.2) NOT NULL,
    preco_total DECIMAL(10.2) NOT NULL,
    observacao VARCHAR(250),

);

