CREATE TYPE status_pedido_enum AS ENUM(
    'CRIADO',
    'CONFIRMADO',
    'ENTREGUE',
    'CANCELADO'
);

CREATE TABLE IF NOT EXISTS pedidos(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subtotal DECIMAL(10.2) NOT NULL,
    taxa_frete DECIMAL(10.2) DEFAULT 0.00,
    valor_total DECIMAL(10.2) NOT NULL,
    data_hora_criacao TIMESTAMP NOT NULL,
    data_confirmacao TIMESTAMP,
    data_cancelamento TIMESTAMP,
    data_entrega TIMESTAMP,
    status_pedido status_pedido_enum NOT NULL,

    CONSTRAINT
);


