CREATE TABLE IF NOT EXISTS cidades(
	id bigint CONSTRAINT pk_cidade_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome_cidade varchar(80) NOT NULL,
	estado_estado varchar(80) NOT NULL,

	CONSTRAINT constraint_check_nome_cidade CHECK (nome_cidade <> ''),
	CONSTRAINT constraint_unique_nome_cidade UNIQUE(nome_cidade)
);

CREATE TABLE IF NOT EXISTS cozinhas(
	id bigint CONSTRAINT pk_cozinha_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(60) NOT NULL CHECK(nome <> '')
);





