CREATE TABLE IF NOT EXISTS formas_pagamento(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(250) NOT NULL,

    CONSTRAINT constraint_check_descricao_forma_pagamento CHECK(descricao <> '')
);

