CREATE TABLE IF NOT EXISTS estados(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(100) NOT NULL,

	CONSTRAINT constraint_check_nome_estado CHECK(nome <> ''),
	CONSTRAINT constraint_unique_nome_estado UNIQUE(nome)
);

