CREATE TABLE IF NOT EXISTS usuarios (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,

    CONSTRAINT constraint_check_nome_usuario CHECK(nome <> ''),
    CONSTRAINT constraint_check_email_usuario CHECK(email <> ''),
    CONSTRAINT constraint_unique_email_usuario UNIQUE(email),
    CONSTRAINT constraint_check_senha_usuario CHECK(senha <> '')
);

