CREATE TABLE IF NOT EXISTS produtos(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(250),
    preco DECIMAL(10,2) NOT NULL,
    ativo boolean NOT NULL,
    restaurante_id bigint NOT NULL,

    CONSTRAINT constraint_check_nome_produto CHECK(nome <> ''),
    CONSTRAINT constraint_unique_nome_produto UNIQUE(nome),
    CONSTRAINT fk_restaurante_id_produto FOREIGN KEY(restaurante_id) REFERENCES restaurantes(id)
);

