CREATE TABLE IF NOT EXISTS cidades(
	id bigint CONSTRAINT pk_cidade_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(100) NOT NULL,
	estado_id bigint NOT NULL,

	CONSTRAINT constraint_check_nome_cidade CHECK(nome <> ''),
	CONSTRAINT constraint_unique_nome_cidade UNIQUE(nome),
	CONSTRAINT fk_estado_id FOREIGN KEY(estado_id) REFERENCES estados(id)
);

