CREATE TABLE IF NOT EXISTS itens_pedido(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(10,2) NOT NULL,
    preco_total DECIMAL(10,2) NOT NULL,
    observacao VARCHAR(250),
    pedido_id bigint NOT NULL,
    produto_id bigint NOT NULL,

    CONSTRAINT fk_pedido_id_item_pedido FOREIGN KEY(pedido_id) REFERENCES pedidos(id),
    CONSTRAINT fk_produto_id_item_pedido FOREIGN KEY(produto_id) REFERENCES produtos(id),
    CONSTRAINT constraint_unique_pedidoproduto_itens_pedido UNIQUE(pedido_id, produto_id)
);

