CREATE TABLE IF NOT EXISTS itens_pedido(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantidade INTEGER NOT NULL,
    preco_unitario DECIMAL(10,2) NOT NULL,
    preco_total DECIMAL(10,2) NOT NULL,
    observacao VARCHAR(250),
    pedido_id bigint NOT NULL,

    CONSTRAINT fk_pedido_id FOREIGN KEY(pedido_id) REFERENCES pedidos(id)
);

