CREATE TABLE IF NOT EXISTS permissoes(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(100) NOT NULL,
    descricao varchar(250) NOT NULL,

    CONSTRAINT constraint_check_nome_permissao CHECK(nome <> ''),
    CONSTRAINT constraint_check_descricao_permissao CHECK(descricao <> '')
);

