CREATE TABLE IF NOT EXISTS estados(
	id bigint CONSTRAINT pk_estado_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(100) NOT NULL,

	CONSTRAINT constraint_check_nome_estado CHECK(nome <> ''),
	CONSTRAINT constraint_unique_nome_estado UNIQUE(nome)
);

CREATE TABLE IF NOT EXISTS cidades(
	id bigint CONSTRAINT pk_cidade_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(100) NOT NULL,
	estado_id bigint NOT NULL,

	CONSTRAINT constraint_check_nome_cidade CHECK(nome <> ''),
	CONSTRAINT constraint_unique_nome_cidade UNIQUE(nome),
	CONSTRAINT fk_estado_id FOREIGN KEY(estado_id) REFERENCES estados(id)
);

CREATE TABLE IF NOT EXISTS cozinhas(
	id bigint CONSTRAINT pk_cozinha_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(100) NOT NULL CHECK(nome <> '')
);



CREATE TABLE IF NOT EXISTS enderecos(
	id bigint CONSTRAINT pk_endereco_id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	cep varchar(10) NOT NULL, 
	logradouro varchar(200) NOT NULL, 
	numero varchar(10),
	complemento varchar(250),
	bairro varchar(100) NOT NULL,
	cidade_id bigint,
	
	
);

insert into cozinhas(id, nome) values(7, 'Bulgara');
insert into cozinhas(nome) values('Bulgara');

select * from estados;
select * from cidades;
select * from cozinhas;
select * from flyway_schema_history;

